### ISSUE TITLE
 automake --add-missing

### ISSUE THREAD

**Issue by jnorthrup** [circulosmeos/gztool#16]
Thanks for the recent release and the mention

this brought me to clean the old source tree and attempt something proper

```
 jim@gentoo ~/work/gztool $ autoreconf && ./configure && make check
configure.ac:4: warning: The macro `AC_PROG_CC_C99' is obsolete.
configure.ac:4: You should run autoupdate.
./lib/autoconf/c.m4:1664: AC_PROG_CC_C99 is expanded from...
configure.ac:4: the top level
configure.ac:3: error: required file './compile' not found
configure.ac:3:   'automake --add-missing' can install 'compile'
[...]
```

some fiddling lead to 

```
jim@gentoo ~/work/gztool $ automake --add-missing
configure.ac:3: installing './compile'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
```
the results changed after that.

```
jim@gentoo ~/work/gztool $ autoreconf && ./configure && make check
configure.ac:4: warning: The macro `AC_PROG_CC_C99' is obsolete.
configure.ac:4: You should run autoupdate.
./lib/autoconf/c.m4:1664: AC_PROG_CC_C99 is expanded from...
configure.ac:4: the top level
checking for a BSD-compatible install... /usr/bin/install -c
```
eventually the makefile was sane.  

just passing this along, i think i can retire my fork for a bit until im ready to figure out an in-browser solution via range requests

**Comment by circulosmeos** [comment]
I'm not sure to understand your request here:

Is the problem this warning? :
```
The macro `AC_PROG_CC_C99' is obsolete
```
This problem arises when using autoconf version >= 2.70, but I'm not sure how to patch this ([without using variables that are not quiet "recommended"](https://gitlab.torproject.org/tpo/core/tor/-/merge_requests/355) but seem to be the only ones to make an .ac file compatible between different autoconf versions), and I must be careful because this `configure.ac` is used to automatically compile the project for Debian and Ubuntu distributions. So any help here is welcome.

**Comment by circulosmeos** [comment]
On the other hand, if you need to use gztool as if it were a **library**, I think I can make it to compile as library and output results to a passed C pointer instead of to stdout.

It would be a work for the caller to ensure that passed pointer points to an enough big memory variable to accommodate the generated output... Don't know if there is a safer way to do this.

**Comment by circulosmeos** [comment]
Hard restrictions.
I wonder why `inflatePrime()` hasn't been ported...

I haven't time now to examine Mark Adler's `gzindex` nor I understand your briefing about it, but I wish you good luck! If I can help you with something let me know, even though my time is very limited nowadays.
